### ISSUE TITLE
i18n YAML trouble

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/commercetools-sunrise-java#268]
```
foo:
  bar:
   title: "Something"
```

Was printing `title: "Something"`. Adding one more level solved the problem:
```
foo:
  bar:
   title: "Something"
   subtitle: "Something else"
```
